require('../../public/assets/design-system/styles/slds.css');

import badge from './badge/example';
import button from './button/example';
import combobox from './combobox/example';
import checkbox from './checkbox/example';
	// import datatable from './datatable/example';
	// import datepicker from './datepicker/example';
	// import dropdown from './dropdown/example';
import notification from './notification/example';
import picklist from './picklist/example';
	// import picker from './picker/example';
import pillbox from './pillbox/example';
	// import popover from './popover/example';
import radio from './radio/example';
import spinner from './spinner/example';
import tree from './tree/example';

badge();
button();
combobox();
checkbox();
	// datatable();
	// datepicker();
	// dropdown();
notification();
picklist();
	// picker();
pillbox();
	// popover();
radio();
spinner();
tree();
