const Samples =  {
  BreadCrumbs1: require('fs').readFileSync('demo/code-snippets/BreadCrumbExamples1.js', 'utf8'),
  Buttons1: require('fs').readFileSync('demo/code-snippets/ButtonExamples1.js', 'utf8'),
  Buttons2: require('fs').readFileSync('demo/code-snippets/ButtonExamples2.js', 'utf8'),
  ButtonGroups1: require('fs').readFileSync('demo/code-snippets/ButtonGroupExamples1.js', 'utf8'),
  ButtonGroups2: require('fs').readFileSync('demo/code-snippets/ButtonGroupExamples2.js', 'utf8'),
  DataTables1: require('fs').readFileSync('demo/code-snippets/DataTableExamples1.js', 'utf8'),
  Dropdowns1: require('fs').readFileSync('demo/code-snippets/DropdownExamples1.js', 'utf8'),
  Dropdowns2: require('fs').readFileSync('demo/code-snippets/DropdownExamples2.js', 'utf8'),
  Icons: require('fs').readFileSync('demo/code-snippets/IconExamples.js', 'utf8'),
  IconButtons: require('fs').readFileSync('demo/code-snippets/ButtonIconExamples.js', 'utf8'),
  Lookups1: require('fs').readFileSync('demo/code-snippets/LookupExamples1.js', 'utf8'),
  Lookups2: require('fs').readFileSync('demo/code-snippets/LookupExamples2.js', 'utf8'),
  Modals1: require('fs').readFileSync('demo/code-snippets/ModalExamples1.js', 'utf8'),
  Modals2: require('fs').readFileSync('demo/code-snippets/ModalExamples2.js', 'utf8'),
  Modals3: require('fs').readFileSync('demo/code-snippets/ModalExamples3.js', 'utf8'),
  Notifications1: require('fs').readFileSync('demo/code-snippets/NotificationExamples1.js', 'utf8'),
  Notifications2: require('fs').readFileSync('demo/code-snippets/NotificationExamples2.js', 'utf8'),
  Notifications3: require('fs').readFileSync('demo/code-snippets/NotificationExamples3.js', 'utf8'),
  PageHeaders1: require('fs').readFileSync('demo/code-snippets/PageHeaderExamples1.js', 'utf8'),
  PageHeaders2: require('fs').readFileSync('demo/code-snippets/PageHeaderExamples2.js', 'utf8'),
  PageHeaders3: require('fs').readFileSync('demo/code-snippets/PageHeaderExamples3.js', 'utf8'),
  PageHeaders4: require('fs').readFileSync('demo/code-snippets/PageHeaderExamples4.js', 'utf8'),
  Picklists: require('fs').readFileSync('demo/code-snippets/PicklistExamples.js', 'utf8'),
  Picklists1: require('fs').readFileSync('demo/code-snippets/PicklistExamples-1.js', 'utf8'),
  CustomPicklists: require('fs').readFileSync('demo/code-snippets/PicklistCustomExamples.js', 'utf8'),
  StatefulButtons1: require('fs').readFileSync('demo/code-snippets/ButtonStatefulExamples1.js', 'utf8'),
  StatefulButtons2: require('fs').readFileSync('demo/code-snippets/ButtonStatefulExamples2.js', 'utf8'),
  Tooltips1: require('fs').readFileSync('demo/code-snippets/TooltipExamples1.js', 'utf8'),
  Tooltips2: require('fs').readFileSync('demo/code-snippets/TooltipExamples2.js', 'utf8'),
  Tooltips3: require('fs').readFileSync('demo/code-snippets/TooltipExamples3.js', 'utf8'),
  DatepickerSingleSelect: require('fs').readFileSync('demo/code-snippets/DateInputExample-1.js', 'utf8'),
  Timepicker: require('fs').readFileSync('demo/code-snippets/TimepickerExample.js', 'utf8'),
};

module.exports = Samples;
